//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqSorgularABarcin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracTramerDetay
    {
        public int AracTramerDetayID { get; set; }
        public int AracParcaID { get; set; }
        public int AracTramerID { get; set; }
        public int TramerDetayID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual AracParca AracParca { get; set; }
        public virtual AracTramer AracTramer { get; set; }
        public virtual TramerDetay TramerDetay { get; set; }
    }
}
