//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqSorgularABarcin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriOzellik
    {
        public int FavoriOzellikID { get; set; }
        public int OzellikBilgiID { get; set; }
        public int FavoriAramaKriterID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual FavoriAramaKriter FavoriAramaKriter { get; set; }
        public virtual OzellikBilgi OzellikBilgi { get; set; }
    }
}
