//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthiwndSorgularLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipperLog
    {
        public int ShipperLogID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string IslemIcerik { get; set; }
    }
}
